language: node_js

node_js:
  - "0.10"
  - "0.11"

install:
  - make GITLAB_URL=http://127.0.0.1 LABOARD_PORT=1337 SOCKETIO_PORT=1337 install

script:
  - cd server
  - node_modules/atoum.js/bin/atoum -d tests
  - cd ../client
  - node_modules/gulp/bin/gulp.js server &
  - node_modules/gulp/bin/gulp.js test

after_script:
  - kill %1
